name: main-check

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'config.example.**'
      - '**.sh'
      - '**.json'
      - '**.yml'
      - '!.github/workflows/**'

jobs:
  Build:

    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
    - uses: actions/checkout@v3

    - name: Check
      run: cargo check

#     - name: Upload Build Artifact
#       uses: actions/upload-artifact@v2.2.2
#       with:
#         name: biliroaming-rust-server-${{ github.run_number }}
#         path: |
#           ./target/release/biliroaming_rust_server
